In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
from keras.models import Sequential,Model
from keras.layers import Input,Dense,Activation

Using TensorFlow backend.


In [2]:
LMS = pd.read_excel('/home/soham/hackerearth_bankloans/93fe009c-2-Foreclosure-Prediction-Dataset_/LMS_31JAN2019.xlsx');

In [98]:
test = pd.read_csv('/home/soham/hackerearth_bankloans/93fe009c-2-Foreclosure-Prediction-Dataset_/test_foreclosure.csv')


In [4]:
train = pd.read_csv('/home/soham/hackerearth_bankloans/93fe009c-2-Foreclosure-Prediction-Dataset_/train_foreclosure.csv')

In [152]:
train.head()

AGREEMENTID  FORECLOSURE
0     11220001            1
1     11220002            1
2     11220006            1
3     11220008            1
4     11220010            1

In [196]:
LMS[LMS['AGREEMENTID']==11220001][['AGREEMENTID','LOAN_AMT','CURRENT_ROI','EMI_DUEAMT','EMI_RECEIVED_AMT','OUTSTANDING_PRINCIPAL','PRE_EMI_DUEAMT','PAID_PRINCIPAL','PAID_INTEREST','LAST_RECEIPT_AMOUNT','LAST_RECEIPT_DATE','ORIGNAL_TENOR','COMPLETED_TENURE']]

AGREEMENTID     LOAN_AMT  CURRENT_ROI    EMI_DUEAMT  EMI_RECEIVED_AMT  \
0         11220001  11710107.24    13.734072  7.516699e+06      7.332154e+06   
2855      11220001  11710107.24    13.734072  7.701243e+06      7.516699e+06   
5825      11220001  11710107.24    13.421934  7.885787e+06      7.701243e+06   
8928      11220001  11710107.24    13.421934  7.885787e+06      7.885787e+06   
12193     11220001  11710107.24    13.421934  8.254876e+06      8.070332e+06   
15534     11220001  11710107.24    13.421934  8.439420e+06      8.254876e+06   
18931     11220001  11710107.24    13.421934  8.614898e+06      8.439420e+06   

       OUTSTANDING_PRINCIPAL  PRE_EMI_DUEAMT  PAID_PRINCIPAL  PAID_INTEREST  \
0               2.262177e+06     7994.273589    9.447930e+06   2.617476e+06   
2855            2.157467e+06     7994.273589    9.552641e+06   2.638213e+06   
5825            2.051797e+06     7994.273589    9.658311e+06   2.657989e+06   
8928            1.944731e+06     7994.273589    9.765377e+06   2.676370e+06   
12193           1.836705e+06     7994.273589    9.873402e+06   2.693792e+06   
15534           1.727712e+06     7994.273589    9.982395e+06   2.710245e+06   
18931           1.164472e+05     7994.273589    1.159366e+07   2.725723e+06   

       LAST_RECEIPT_AMOUNT LAST_RECEIPT_DATE  ORIGNAL_TENOR  COMPLETED_TENURE  
0                  83559.0        2013-11-01            120                39  
2855               83559.0        2013-12-01            120                40  
5825               83559.0        2014-01-01            120                41  
8928               83559.0        1974-02-02            120                41  
12193              83559.0        2014-03-01            120                43  
15534              83559.0        2014-04-01            120                44  
18931            1000000.0        2014-05-05            120                45

In [31]:
LMS[LMS['AGREEMENTID']==11220016][['LOAN_AMT','CURRENT_ROI','EMI_DUEAMT','OUTSTANDING_PRINCIPAL','PRE_EMI_DUEAMT','PAID_PRINCIPAL','PAID_INTEREST','LAST_RECEIPT_AMOUNT','ORIGNAL_TENOR','COMPLETED_TENURE']]

LOAN_AMT  CURRENT_ROI    EMI_DUEAMT  OUTSTANDING_PRINCIPAL  \
15      8407256.48    13.734072  3.650597e+06           5.031202e+06   
2868    8407256.48    13.734072  3.761221e+06           5.002122e+06   
5838    8407256.48    13.421934  3.871846e+06           4.972777e+06   
8941    8407256.48    13.421934  3.871846e+06           4.942126e+06   
12206   8407256.48    13.421934  4.093094e+06           4.911201e+06   
15547   8407256.48    13.421934  4.203718e+06           4.879999e+06   
18944   8407256.48    13.421934  4.314342e+06           4.848517e+06   
22626   8407256.48    13.421934  4.424966e+06           4.816753e+06   
26499   8407256.48    13.421934  4.535591e+06           4.784705e+06   
30383   8407256.48    13.421934  4.646215e+06           4.752370e+06   
34507   8407256.48    13.421934  4.756839e+06           4.719746e+06   
38774   8407256.48    13.421934  4.867463e+06           4.686828e+06   
43146   8407256.48    13.421934  4.978087e+06           4.653616e+06   
47657   8407256.48    13.421934  5.088711e+06           4.620106e+06   
52331   8407256.48    13.421934  5.199336e+06           4.586295e+06   
57137   8407256.48    13.421934  5.309960e+06           4.552183e+06   
62110   8407256.48    13.421934  5.420584e+06           4.517764e+06   
67285   8407256.48    13.421934  6.084329e+06           4.304684e+06   
73397   8407256.48    13.421934  6.194953e+06           4.268048e+06   
79697   8407256.48    12.797658  6.305577e+06           4.231084e+06   
86117   8407256.48    12.797658  6.416201e+06           4.193789e+06   
92751   8407256.48    12.797658  6.526826e+06           4.156161e+06   
99584   8407256.48    12.797658  6.637450e+06           4.116463e+06   
106649  8407256.48    12.797658  6.748074e+06           4.076426e+06   
114012  8407256.48    12.797658  6.858698e+06           4.036047e+06   
121536  8407256.48    12.797658  6.969322e+06           3.995323e+06   
129232  8407256.48    12.797658  6.985754e+06           9.516596e+05   
137235  8407256.48    12.797658  7.002185e+06           9.503285e+05   
145562  8407256.48    12.797658  7.018617e+06           9.472763e+05   
154047  8407256.48    12.797658  7.035049e+06           9.441980e+05   
162876  8407256.48    12.797658  7.051480e+06           9.410934e+05   
171927  8407256.48    12.797658  7.067912e+06           9.379622e+05   
181172  8407256.48    12.797658  7.084344e+06           9.348043e+05   
190615  8407256.48    12.797658  7.100775e+06           9.316195e+05   
200231  8407256.48    12.797658  7.117207e+06           9.284073e+05   
596494  8407256.48    13.421934  5.531208e+06           4.483038e+06   
596495  8407256.48    13.421934  5.641832e+06           4.448001e+06   
596496  8407256.48    13.421934  5.752456e+06           4.412649e+06   
596497  8407256.48    13.421934  5.863081e+06           4.376982e+06   
596498  8407256.48    13.421934  5.973705e+06           4.340994e+06   

        PRE_EMI_DUEAMT  PAID_PRINCIPAL  PAID_INTEREST  LAST_RECEIPT_AMOUNT  \
15        185120.82864    3.376055e+06   1.848112e+06              50089.0   
2868      185120.82864    3.405134e+06   1.894231e+06              50089.0   
5838      185120.82864    3.434480e+06   1.940084e+06              50089.0   
8941      185120.82864    3.465130e+06   1.984632e+06              50089.0   
12206     185120.82864    3.496055e+06   2.028905e+06              50089.0   
15547     185120.82864    3.527258e+06   2.072901e+06              50089.0   
18944     185120.82864    3.558739e+06   2.116618e+06              50089.0   
22626     185120.82864    3.590503e+06   2.160052e+06              50089.0   
26499     185120.82864    3.622551e+06   2.203203e+06              50089.0   
30383     185120.82864    3.654886e+06   2.246066e+06              50089.0   
34507     185120.82864    3.687511e+06   2.288640e+06              50089.0   
38774     185120.82864    3.720428e+06   2.330921e+06              50089.0   
43146     185120.82864    3.753640e+06   2.

In [153]:
LMS.columns

Index(['AGREEMENTID', 'CUSTOMERID', 'LOAN_AMT', 'NET_DISBURSED_AMT',
       'INTEREST_START_DATE', 'CURRENT_ROI', 'ORIGNAL_ROI', 'CURRENT_TENOR',
       'ORIGNAL_TENOR', 'DUEDAY', 'AUTHORIZATIONDATE', 'CITY',
       'PRE_EMI_DUEAMT', 'PRE_EMI_RECEIVED_AMT', 'PRE_EMI_OS_AMOUNT',
       'EMI_DUEAMT', 'EMI_RECEIVED_AMT', 'EMI_OS_AMOUNT', 'EXCESS_AVAILABLE',
       'EXCESS_ADJUSTED_AMT', 'BALANCE_EXCESS', 'NET_RECEIVABLE',
       'OUTSTANDING_PRINCIPAL', 'PAID_PRINCIPAL', 'PAID_INTEREST',
       'MONTHOPENING', 'LAST_RECEIPT_DATE', 'LAST_RECEIPT_AMOUNT', 'NET_LTV',
       'COMPLETED_TENURE', 'BALANCE_TENURE', 'DPD', 'FOIR', 'PRODUCT',
       'SCHEMEID', 'NPA_IN_LAST_MONTH', 'NPA_IN_CURRENT_MONTH', 'MOB'],
      dtype='object')

In [5]:
agreement_ids = LMS['AGREEMENTID'].unique()
len(agreement_ids)

33354

In [6]:
COUNT = 0
Lms_cleaned = pd.DataFrame(columns=['AGREEMENTID','CUSTOMERID','LOAN_AMT','ROI','PRE_EMI','EMI','EMI_PAID','TOTAL_PAID','AVG_RECEIPT','TENURE','HL','LAP','STHL','STLAP'])
Lms_cleaned['AGREEMENTID'] = agreement_ids 
Lms_cleaned.set_index('AGREEMENTID', inplace = True)
for i in agreement_ids:
    Lms_i= LMS[LMS['AGREEMENTID']==i]
    Lms_cleaned.loc[i]['CUSTOMERID'] = Lms_i.iloc[0]['CUSTOMERID']
    Lms_cleaned.loc[i]['LOAN_AMT'] = Lms_i.iloc[0]['LOAN_AMT']
    Lms_cleaned.loc[i]['ROI'] = Lms_i.iloc[0]['CURRENT_ROI']
    Lms_cleaned.loc[i]['PRE_EMI'] = np.average(Lms_i['PRE_EMI_DUEAMT'])
    if len(Lms_i['EMI_DUEAMT'])>1:
        Lms_cleaned.loc[i]['EMI'] = Lms_i.iloc[1]['EMI_DUEAMT'] - Lms_i.iloc[0]['EMI_DUEAMT']
    else:
        if Lms_i.iloc[0]['COMPLETED_TENURE'] == 0:
             Lms_cleaned.loc[i]['EMI'] = Lms_i.iloc[0]['EMI_DUEAMT']
        else:        
             Lms_cleaned.loc[i]['EMI'] = Lms_i.iloc[0]['EMI_DUEAMT']/Lms_i.iloc[0]['COMPLETED_TENURE']
    Lms_cleaned.loc[i]['EMI_PAID'] = int(sum(Lms_i['EMI_DUEAMT'] - Lms_i['EMI_RECEIVED_AMT']) == 0)
    if len(Lms_i['EMI_DUEAMT'])>1:
        Lms_cleaned.loc[i]['TOTAL_PAID'] = (Lms_i.iloc[1]['PAID_INTEREST'] - Lms_i.iloc[0]['PAID_INTEREST'])+(Lms_i.iloc[1]['PAID_PRINCIPAL'] - Lms_i.iloc[0]['PAID_PRINCIPAL'])
    else:
        if Lms_i.iloc[0]['COMPLETED_TENURE'] == 0:
            Lms_cleaned.loc[i]['TOTAL_PAID'] = (Lms_i.iloc[0]['PAID_INTEREST'] +Lms_i.iloc[0]['PAID_PRINCIPAL'])
        else:
            Lms_cleaned.loc[i]['TOTAL_PAID'] = (Lms_i.iloc[0]['PAID_INTEREST'] +Lms_i.iloc[0]['PAID_PRINCIPAL'])/Lms_i.iloc[0]['COMPLETED_TENURE']
    #Lms_cleaned.loc[i]['AVG_RECEIPT'] = np.average(Lms_i['LAST_RECEIPT_AMOUNT'])
    Lms_cleaned.loc[i]['TENURE'] = Lms_i.iloc[0]['ORIGNAL_TENOR']
    Lms_cleaned.loc[i]['HL'] = int(Lms_i.iloc[0]['PRODUCT'] == 'HL')
    Lms_cleaned.loc[i]['LAP'] = int(Lms_i.iloc[0]['PRODUCT'] == 'LAP')
    Lms_cleaned.loc[i]['STHL'] = int(Lms_i.iloc[0]['PRODUCT'] == 'STHL')
    Lms_cleaned.loc[i]['STLAP'] = int(Lms_i.iloc[0]['PRODUCT'] == 'STLAP')
    COUNT +=1
    if COUNT%1000 ==0:
        print(COUNT)
    
Lms_cleaned

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000


CUSTOMERID     LOAN_AMT      ROI  PRE_EMI      EMI EMI_PAID  \
AGREEMENTID                                                                 
11220001      1.2001e+07  1.17101e+07  13.7341  7994.27   184544        0   
11220002      1.2001e+07  1.92903e+07  13.7341   100505   279448        0   
11220003      1.2001e+07   4.0535e+06  17.1676        0  68239.8        1   
11220004      1.2001e+07   1.3257e+07  15.6069  28441.7   194918        1   
11220005      1.2001e+07  1.32114e+07  16.5433        0   202948        1   
11220006      1.2001e+07  3.93339e+06  16.2312  5947.63  62983.5        1   
11220007      1.2001e+07  6.15531e+06  16.5433   451448   104347        1   
11220008      1.2001e+07  1.00226e+07  13.7341  60322.2   145192        0   
11220009      1.2001e+07  9.49928e+06  18.9156   188502   178778        0   
11220010      1.2001e+07  7.75594e+06  15.6069  27732.8   120218        1   
11220011      1.2001e+07       954408  13.7341  1325.13  13827.7        0   
11220012      1.2001e+07   6.6057e+06  15.6069  37790.5  95533.1        0   
11220013      1.2001e+07  5.40066e+06  13.7341  5627.39  75269.7        0   
11220014      1.2001e+07  3.29603e+07  13.7341   225933   464308        0   
11220015      1.2001e+07  4.30872e+06  17.4797  24033.5    73971        0   
11220016      1.2001e+07  8.40726e+06  13.7341   185121   110624        0   
11220017      1.2001e+07       975842  17.4797  1674.08  16756.3        0   
11220018      1.2001e+07  7.68864e+06  16.5433        0   118111        1   
11220019      1.2001e+07   1.7252e+07  13.7341   167786   269322        0   
11220020      1.2001e+07  1.46649e+07  15.6069   141577   215617        1   
11220021      1.2001e+07  4.34378e+06  13.4219        0  70870.2        1   
11220022      1.2001e+07  4.08065e+06  13.7341        0   102126        1   
11220023      1.2001e+07  1.13752e+07  19.0404  20453.4   230513        1   
11220024      1.2001e+07  3.41853e+06  13.7341        0  47967.5        0   
11220025      1.2001e+07   2.1665e+06  14.0462        0  31372.5        1   
11220026      1.2001e+07  3.75324e+06  15.6069  39747.3  58405.2        1   
11220027      1.2001e+07  4.09404e+06  15.6069   547451  65269.3        1   
11220028      1.2001e+07  7.65661e+06  13.7341   7979.5   111620        0   
11220029      1.2001e+07  9.00777e+06  14.0462        0   129328        1   
11220030      1.2001e+07  4.61319e+06  15.2948        0  20612.4        1   
...                  ...          ...      ...      ...      ...      ...   
11253325             NaN  3.00259e+06  17.4173        0        0        1   
11253326             NaN  4.50389e+06  14.9826        0        0        1   
11253327             NaN  1.68145e+06  13.1098        0        0        1   
11253328             NaN  1.71148e+06  14.9202        0        0        1   
11253329             NaN  4.50389e+06  13.4219        0        0        1   
11253330             NaN   2.7774e+06  13.4219        0        0        1   
11253331             NaN  3.11638e+06  13.1098        0        0        1   
11253332             NaN  2.76989e+06  13.1098        0        0        1   
11253333             NaN  4.50389e+06  13.2347        0        0        1   
11253334     1.20339e+07  7.95687e+06  13.7341  10730.2        0        1   
11253335     1.20339e+07  1.66644e+07  14.6705  24004.8        0        1   
11253336     1.20339e+07       615531  17.4797        0        0        1   
11253337     1.20339e+07  7.22016e+06  15.2948        0        0        1   
11253338     1.20339e+07  1.82402e+06   15.919        0        0        1   
11253339     1.20339e+07  7.77976e+06  13.4219  10253.2        0        1   
11253340     1.20339e+07  7.50648e+06  14.3583  10583.4        0        1   
11253341     1.20339e+07  7.20622e+06  15.2948        0   140846        1   
11253342     1.20339e+07  3.00259e+06  19.9768        0        0        1   
11253343     1.20339e+07  5.25066e+06  13.4219        0        0        1   
11253344  

In [7]:
ld = Lms_cleaned.drop(['AVG_RECEIPT'],axis = 1)
Lms_cleaned = ld

In [12]:
Lms_cleaned_nonan = Lms_cleaned.dropna()

In [13]:
Lms_cleaned_nonan

CUSTOMERID     LOAN_AMT      ROI  PRE_EMI      EMI EMI_PAID  \
AGREEMENTID                                                                 
11220001      1.2001e+07  1.17101e+07  13.7341  7994.27   184544        0   
11220002      1.2001e+07  1.92903e+07  13.7341   100505   279448        0   
11220003      1.2001e+07   4.0535e+06  17.1676        0  68239.8        1   
11220004      1.2001e+07   1.3257e+07  15.6069  28441.7   194918        1   
11220005      1.2001e+07  1.32114e+07  16.5433        0   202948        1   
11220006      1.2001e+07  3.93339e+06  16.2312  5947.63  62983.5        1   
11220007      1.2001e+07  6.15531e+06  16.5433   451448   104347        1   
11220008      1.2001e+07  1.00226e+07  13.7341  60322.2   145192        0   
11220009      1.2001e+07  9.49928e+06  18.9156   188502   178778        0   
11220010      1.2001e+07  7.75594e+06  15.6069  27732.8   120218        1   
11220011      1.2001e+07       954408  13.7341  1325.13  13827.7        0   
11220012      1.2001e+07   6.6057e+06  15.6069  37790.5  95533.1        0   
11220013      1.2001e+07  5.40066e+06  13.7341  5627.39  75269.7        0   
11220014      1.2001e+07  3.29603e+07  13.7341   225933   464308        0   
11220015      1.2001e+07  4.30872e+06  17.4797  24033.5    73971        0   
11220016      1.2001e+07  8.40726e+06  13.7341   185121   110624        0   
11220017      1.2001e+07       975842  17.4797  1674.08  16756.3        0   
11220018      1.2001e+07  7.68864e+06  16.5433        0   118111        1   
11220019      1.2001e+07   1.7252e+07  13.7341   167786   269322        0   
11220020      1.2001e+07  1.46649e+07  15.6069   141577   215617        1   
11220021      1.2001e+07  4.34378e+06  13.4219        0  70870.2        1   
11220022      1.2001e+07  4.08065e+06  13.7341        0   102126        1   
11220023      1.2001e+07  1.13752e+07  19.0404  20453.4   230513        1   
11220024      1.2001e+07  3.41853e+06  13.7341        0  47967.5        0   
11220025      1.2001e+07   2.1665e+06  14.0462        0  31372.5        1   
11220026      1.2001e+07  3.75324e+06  15.6069  39747.3  58405.2        1   
11220027      1.2001e+07  4.09404e+06  15.6069   547451  65269.3        1   
11220028      1.2001e+07  7.65661e+06  13.7341   7979.5   111620        0   
11220029      1.2001e+07  9.00777e+06  14.0462        0   129328        1   
11220030      1.2001e+07  4.61319e+06  15.2948        0  20612.4        1   
...                  ...          ...      ...      ...      ...      ...   
11252923     1.20339e+07   1.5813e+06  14.0462        0        0        1   
11252924     1.20339e+07       285246  15.8566        0        0        1   
11252925     1.20339e+07  2.13124e+06  13.4219        0        0        1   
11252926     1.20339e+07  2.36702e+06  17.4173        0        0        1   
11252927     1.20339e+07  1.65593e+06  14.6705        0        0        1   
11252928     1.20339e+07  2.02675e+06  14.6705        0        0        1   
11252929     1.20339e+07  2.28181e+06  17.4173        0        0        1   
11252930     1.20339e+07  3.43555e+06  14.6705        0        0        1   
11252931     1.20339e+07  1.12674e+06  13.4219        0        0        1   
11253334     1.20339e+07  7.95687e+06  13.7341  10730.2        0        1   
11253335     1.20339e+07  1.66644e+07  14.6705  24004.8        0        1   
11253336     1.20339e+07       615531  17.4797        0        0        1   
11253337     1.20339e+07  7.22016e+06  15.2948        0        0        1   
11253338     1.20339e+07  1.82402e+06   15.919        0        0        1   
11253339     1.20339e+07  7.77976e+06  13.4219  10253.2        0        1   
11253340     1.20339e+07  7.50648e+06  14.3583  10583.4        0        1   
11253341     1.20339e+07  7.20622e+06  15.2948        0   140846        1   
11253342     1.20339e+07  3.00259e+06  19.9768        0        0        1   
11253343     1.20339e+07  5.25066e+06  13.4219        0        0        1   
11253344  

In [14]:
len(Lms_cleaned) - len(Lms_cleaned_nonan)

459

In [100]:
Lms_clean_joined = pd.merge(Lms_cleaned_nonan,train,left_index = True, right_on = "AGREEMENTID")
Lms_clean_joined

CUSTOMERID     LOAN_AMT      ROI  PRE_EMI          EMI EMI_PAID  \
0       1.2001e+07  1.17101e+07  13.7341  7994.27       184544        0   
1       1.2001e+07  1.92903e+07  13.7341   100505       279448        0   
2       1.2001e+07  3.93339e+06  16.2312  5947.63      62983.5        1   
3       1.2001e+07  1.00226e+07  13.7341  60322.2       145192        0   
4       1.2001e+07  7.75594e+06  15.6069  27732.8       120218        1   
5       1.2001e+07       954408  13.7341  1325.13      13827.7        0   
6       1.2001e+07   6.6057e+06  15.6069  37790.5      95533.1        0   
7       1.2001e+07  3.29603e+07  13.7341   225933       464308        0   
8       1.2001e+07  8.40726e+06  13.7341   185121       110624        0   
9       1.2001e+07       975842  17.4797  1674.08      16756.3        0   
10      1.2001e+07  1.46649e+07  15.6069   141577       215617        1   
11      1.2001e+07  4.34378e+06  13.4219        0      70870.2        1   
12      1.2001e+07  4.08065e+06  13.7341        0       102126        1   
13      1.2001e+07   2.1665e+06  14.0462        0      31372.5        1   
14      1.2001e+07  3.75324e+06  15.6069  39747.3      58405.2        1   
15      1.2001e+07  9.00777e+06  14.0462        0       129328        1   
16      1.2001e+07  4.61319e+06  15.2948        0      20612.4        1   
17      1.2001e+07  6.38051e+07  15.6069   228141       989356        0   
18      1.2001e+07  6.00518e+07  19.0404        0  1.21691e+06        1   
19      1.2001e+07  6.15722e+06  16.5433        0        87642        1   
20      1.2001e+07  7.82946e+06  14.0462        0       111550        1   
21      1.2001e+07  6.91978e+06  16.2312        0       110165        1   
22      1.2001e+07  5.02934e+07  16.5433   694678       873321        1   
23      1.2001e+07  7.65661e+06  18.4161   165633       155157        1   
24      1.2001e+07  3.27428e+07  15.6069        0       502982        0   
25      1.2001e+07  2.33076e+07  18.4161   157154       472314        1   
26      1.2001e+07   1.4525e+07  18.4161    97936       294343        1   
27      1.2001e+07  7.80674e+06  15.6069  36368.2       123847        1   
28      1.2001e+07  5.38205e+06   15.482        0      82200.1        1   
29      1.2001e+07  7.58154e+06  18.4161  85199.3       282695        1   
...            ...          ...      ...      ...          ...      ...   
19734  1.20339e+07  2.25194e+06  17.4173        0            0        1   
19735  1.20339e+07  2.25194e+06  14.6705        0            0        1   
19736  1.20339e+07  1.49947e+06  16.2312        0            0        1   
19737  1.20339e+07  1.14098e+06  13.4219        0            0        1   
19738  1.20339e+07  2.81708e+06  14.3583        0            0        1   
19739  1.20339e+07  1.74555e+06  17.4173        0            0        1   
19740  1.20339e+07  2.25194e+06  17.4173        0            0        1   
19741  1.20339e+07  1.65143e+06  14.6705        0            0        1   
19742  1.20339e+07  1.10011e+06  14.0462        0            0        1   
19743  1.20339e+07  2.36702e+06  17.4173        0            0        1   
19744  1.20339e+07  1.65593e+06  14.6705        0            0        1   
19745  1.20339e+07  2.02675e+06  14.6705        0            0        1   
19746  1.20339e+07  2.28181e+06  17.4173        0            0        1   
19747  1.20339e+07  3.43555e+06  14.6705        0            0        1   
19996  1.20339e+07  1.66644e+07  14.6705  24004.8            0        1   
19997  1.20339e+07  7.22016e+06  15.2948        0            0        1   
19998  1.20339e+07  1.82402e+06   15.919        0            0        1   
19999  1.20339e+07  7.77976e+06  13.4219  10253.2            0        1   
20000  1.20339e+07  7.50648e+06  14.3583  10583.4            0        1   
20001  1.20339e+07  7.20622e+06  15.2948        0       140846        1   
20002  1.20339e+07  2.17688e+06  17.4797  3736.87            0        1   
20003  1.20339e+07  2.67264e+06  

In [102]:
labels_only_lms = Lms_clean_joined['FORECLOSURE']
Lms_clean_joined = Lms_clean_joined.drop(['FORECLOSURE'],axis = 1)

In [103]:
Lms_clean_joined['CUSTOMERID'] = Lms_clean_joined['CUSTOMERID'].astype(np.int64)
type(Lms_clean_joined['CUSTOMERID'][0])

numpy.int64

In [55]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [17]:
dg =  pd.read_excel('/home/soham/hackerearth_bankloans/93fe009c-2-Foreclosure-Prediction-Dataset_/Customers_31JAN2019.xlsx');

In [19]:
custtypeid_oh = pd.get_dummies(dg['CUST_CONSTTYPE_ID'])
custtypeid_oh.columns = ['CUST_CONSTTYPE_ID_1','CUST_CONSTTYPE_ID_2','CUST_CONSTTYPE_ID_3','CUST_CONSTTYPE_ID_4','CUST_CONSTTYPE_ID_5','CUST_CONSTTYPE_ID_6']
dg1 = pd.concat([dg,custtypeid_oh],axis = 1)
custcatid_oh = pd.get_dummies(dg['CUST_CATEGORYID'])
custcatid_oh.columns = ['CUST_CATEGORYID_4','CUST_CATEGORYID_5','CUST_CATEGORYID_6','CUST_CATEGORYID_7','CUST_CATEGORYID_8']
dg1 = pd.concat([dg1,custcatid_oh],axis = 1)
sex = pd.get_dummies(dg['SEX'])
sex.columns = ['FEMALE','MALE']
married = pd.get_dummies(dg['MARITAL_STATUS'])
married.columns = ['MARRIED','SINGLE']
qual = pd.get_dummies(dg['QUALIFICATION'])
dg1 = pd.concat([dg1,sex,married,qual],axis = 1)

In [20]:
dg2 = dg1.drop(['CUST_CONSTTYPE_ID','CUST_CATEGORYID','PROFESSION','SEX','MARITAL_STATUS','QUALIFICATION','OCCUPATION','POSITION'],axis = 1)
dg2['PRE_JOBYEARS'] = dg2['PRE_JOBYEARS'].fillna(0)
dg2

CUSTOMERID   AGE  NO_OF_DEPENDENT  GROSS_INCOME  PRE_JOBYEARS  \
0       12001000  33.0              0.0  1.983752e+05           8.0   
1       12001001  44.0              0.0  2.427040e+05          10.0   
2       12001002  50.0              0.0  0.000000e+00           0.0   
3       12001003  40.0              0.0  3.652635e+05           0.0   
4       12001004  27.0              0.0  1.873422e+05           0.0   
5       12001005  43.0              0.0  5.353621e+04           0.0   
6       12001006  48.0              0.0  4.984215e+04           0.0   
7       12001007  33.0              0.0  1.233705e+05           7.0   
8       12001008  44.0              0.0  1.833320e+05           0.0   
9       12001009  37.0              0.0  9.380384e+04           0.0   
10      12001010  30.0              0.0  3.588097e+04           5.0   
11      12001011  33.0              0.0  6.357687e+04           0.0   
12      12001012  29.0              0.0  1.080933e+05           1.0   
13      12001013  32.0              0.0  3.317578e+05           5.0   
14      12001014  30.0              0.0  5.953539e+04           8.0   
15      12001015  41.0              0.0  9.515663e+04           0.0   
16      12001017  49.0              0.0  9.013217e+04           0.0   
17      12001018  42.0              0.0  1.102122e+06          14.0   
18      12001019  34.0              0.0  1.337198e+05           0.0   
19      12001020  32.0              0.0  7.709754e+04           3.0   
20      12001021  62.0              0.0  1.501296e+00           0.0   
21      12001022  37.0              0.0  1.898736e+05           0.0   
22      12001023  25.0              0.0  3.440970e+04           0.0   
23      12001024  28.0              0.0  4.954276e+04           2.0   
24      12001025  35.0              0.0  4.199512e+04           0.0   
25      12001026  26.0              0.0  7.884205e+04           0.0   
26      12001027  32.0              0.0  9.007775e+04           0.0   
27      12001028  31.0              0.0  8.932109e+04           0.0   
28      12001029  34.0              0.0  0.000000e+00           0.0   
29      12001030  25.0              0.0  4.543563e+05           0.0   
...          ...   ...              ...           ...           ...   
9970    12014070  33.0              3.0  3.405089e+04           0.0   
9971    12014080  48.0              0.0  9.241527e+04           0.0   
9972    12014074  61.0              0.0  5.254535e+04           0.0   
9973    12014083  34.0              0.0  0.000000e+00           0.0   
9974    12014086  35.0              0.0  9.054465e+04           0.0   
9975    12014088  23.0              0.0  3.678050e+04           0.0   
9976    12014075  33.0              0.0  5.938087e+04           0.0   
9977    12014102  30.0              0.0  3.047630e+04           0.0   
9978    12014103  28.0              0.0  6.445363e+04           0.0   
9979    12014106  54.0              0.0  2.899185e+05           0.0   
9980    12014108  49.0              0.0  9.931947e+04           0.0   
9981    12014113  49.0              0.0  1.131465e+05           0.0   
9982    12014118  30.0              0.0  1.430104e+05           0.0   
9983    12014122  66.0              0.0  1.201037e-01           0.0   
9984    12014124  38.0              0.0  9.772235e+04           0.0   
9985    12014133  52.0              0.0  7.656609e+04           0.0   
9986    12014134  37.0              0.0  7.432064e+04           0.0   
9987    12014143  35.0              4.0  1.243032e+05           0.0   
9988    12014162  49.0              0.0  1.125972e+05           0.0   
9989    12014170  43.0              0.0  1.320108e+05           0.0   
9990    12014173  49.0              5.0  5.177262e+04           0.0   
9991    12014174  36.0              0.0  4.503887e+04           5.0   
9992    12014177  52.0              0.0  3.471596e+04           0.0   
9993    12014184  26.0              0.0  4.284548e+04           0.0   
9994    12014187  38.0        

In [21]:
dg2[dg2.isnull().values]

CUSTOMERID   AGE  NO_OF_DEPENDENT  GROSS_INCOME  PRE_JOBYEARS  \
37      12001039   NaN              0.0      0.000000           0.0   
63      12001070   NaN              0.0      0.000000           0.0   
71      12001082   NaN              0.0      0.000000           0.0   
72      12001086   NaN              0.0      0.000000           0.0   
73      12001087   NaN              0.0      0.000000           0.0   
74      12001088   NaN              NaN      0.000000           0.0   
74      12001088   NaN              NaN      0.000000           0.0   
74      12001088   NaN              NaN      0.000000           0.0   
82      12001099   NaN              0.0      0.000000           0.0   
87      12001106   NaN              0.0      0.000000           0.0   
90      12001109   NaN              NaN      0.000000           0.0   
90      12001109   NaN              NaN      0.000000           0.0   
90      12001109   NaN              NaN      0.000000           0.0   
100     12001130   NaN              0.0      0.000000           0.0   
114     12001149   NaN              0.0      0.000000           0.0   
123     12001159   NaN              0.0      0.000000           0.0   
142     12001187   NaN              0.0      0.000000           0.0   
158     12001213   NaN              NaN      0.000000           0.0   
158     12001213   NaN              NaN      0.000000           0.0   
158     12001213   NaN              NaN      0.000000           0.0   
163     12001220   NaN              0.0      0.000000           0.0   
178     12001240   NaN              0.0      0.000000           0.0   
217     12001304   NaN              0.0      0.000000           0.0   
230     12001317   NaN              0.0      0.000000           0.0   
251     12001363   NaN              0.0      0.000000           0.0   
273     12001396   NaN              0.0      0.000000           0.0   
276     12001400   NaN              0.0      0.000000           0.0   
290     12001420   NaN              0.0      0.000000           0.0   
318     12001454   NaN              NaN      0.000000           0.0   
318     12001454   NaN              NaN      0.000000           0.0   
...          ...   ...              ...           ...           ...   
8833    12012384   NaN              0.0      0.000000           0.0   
8901    12012430   NaN              0.0      0.000000           0.0   
8993    12012481   NaN              0.0      0.000000           0.0   
9050    12012507   NaN              0.0      0.000000           0.0   
9157    12012749   NaN              0.0      0.000000           0.0   
9162    12012751   NaN              0.0      0.000000           0.0   
9219    12013198   NaN              0.0      0.000000           0.0   
9234    12012988  45.0              NaN      1.501296           0.0   
9244    12012806   NaN              0.0      0.000000           0.0   
9302    12013511   NaN              0.0      0.000000           0.0   
9321    12013214   NaN              0.0      0.000000           0.0   
9346    12013040   NaN              0.0      0.000000           0.0   
9347    12013218   NaN              0.0      0.000000           0.0   
9375    12012864   NaN              0.0      0.000000           0.0   
9412    12013517   NaN              0.0      0.000000           0.0   
9434    12013247   NaN              0.0      0.000000           0.0   
9546    12013150   NaN              0.0      0.000000           0.0   
9554    12013791   NaN              0.0      0.000000           0.0   
9655    12013556   NaN              0.0      0.000000           0.0   
9657    12013799   NaN              0.0      0.000000           0.0   
9662    12013559   NaN              0.0      0.000000           0.0   
9725    12013809   NaN              0.0      0.000000           0.0   
9726    12013582   NaN              0.0      0.000000           0.0   
9789    12013614   NaN              0.0      0.000000           0.0   
9790    12013495   NaN        

In [22]:
dg2['NO_OF_DEPENDENT'] = dg2['NO_OF_DEPENDENT'].fillna(0)
dg2['AGE'] = dg2['AGE'].fillna(dg2['AGE'].mean())

In [41]:
len(dg2)

10000

In [52]:
lms_dg2 = pd.merge(Lms_clean_joined,dg2)
len(lms_dg2)

5992

In [49]:
len(LMS['AGREEMENTID'].unique())

33354

In [24]:
dg2 = dg2.drop(['BRANCH_PINCODE'],axis = 1)
dg2.head()

CUSTOMERID   AGE  NO_OF_DEPENDENT   GROSS_INCOME  PRE_JOBYEARS  \
0    12001000  33.0              0.0  198375.221829           8.0   
1    12001001  44.0              0.0  242703.982915          10.0   
2    12001002  50.0              0.0       0.000000           0.0   
3    12001003  40.0              0.0  365263.511624           0.0   
4    12001004  27.0              0.0  187342.198995           0.0   

   NETTAKEHOMEINCOME  CUST_CONSTTYPE_ID_1  CUST_CONSTTYPE_ID_2  \
0      198375.221829                    1                    0   
1      242703.982915                    1                    0   
2           0.000000                    1                    0   
3      365263.516128                    0                    0   
4      187342.198995                    0                    0   

   CUST_CONSTTYPE_ID_3  CUST_CONSTTYPE_ID_4 ...  MARRIED  SINGLE  DOCTRATE  \
0                    0                    0 ...        1       0         0   
1                    0                    0 ...        1       0         0   
2                    0                    0 ...        1       0         0   
3                    1                    0 ...        1       0         0   
4                    1                    0 ...        1       0         0   

   ENG  GRAD  MAT  OTHERS  POSTGRAD  PRF  UG  
0    0     0    0       0         1    0   0  
1    0     0    0       0         1    0   0  
2    0     1    0       0         0    0   0  
3    0     1    0       0         0    0   0  
4    0     1    0       0         0    0   0  

[5 rows x 29 columns]

In [25]:
dg2.isnull().values.any()

False

In [104]:
Lms_clean_joined.drop(['CUSTOMERID','AGREEMENTID'],inplace = True,axis = 1)

In [105]:
Lms_clean_joined.shape

(19731, 11)

In [110]:
model1 = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model1.add(Dense(32, activation='relu', input_dim=11))
model1.add(Dense(16, activation='relu'))
model1.add(Dense(1, activation='relu'))

In [113]:
model1.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

In [114]:
model1.fit(Lms_clean_joined, labels_only_lms, epochs = 10, batch_size = 64,validation_split=0.2)

Train on 15784 samples, validate on 3947 samples
Epoch 1/10
15784/15784 [==============================] - 1s 42us/step - loss: 0.1136 - acc: 0.8864 - val_loss: 5.0671e-04 - val_acc: 0.9995
Epoch 2/10
15784/15784 [==============================] - 0s 27us/step - loss: 0.1136 - acc: 0.8864 - val_loss: 5.0671e-04 - val_acc: 0.9995
Epoch 3/10
15784/15784 [==============================] - 0s 27us/step - loss: 0.1136 - acc: 0.8864 - val_loss: 5.0671e-04 - val_acc: 0.9995
Epoch 4/10
15784/15784 [==============================] - 0s 26us/step - loss: 0.1136 - acc: 0.8864 - val_loss: 5.0671e-04 - val_acc: 0.9995
Epoch 5/10
15784/15784 [==============================] - 0s 27us/step - loss: 0.1136 - acc: 0.8864 - val_loss: 5.0671e-04 - val_acc: 0.9995
Epoch 6/10
15784/15784 [==============================] - 0s 27us/step - loss: 0.1136 - acc: 0.8864 - val_loss: 5.0671e-04 - val_acc: 0.9995
Epoch 7/10
15784/15784 [==============================] - 0s 27us/step - loss: 0.1136 - acc: 0.8864 - val

In [116]:
lms_cleaned_predict = pd.merge(Lms_cleaned_nonan,test, left_index=True, right_on = 'AGREEMENTID' )
lms_cleaned_predict.drop(['CUSTOMERID','AGREEMENTID','FORECLOSURE'], inplace = True, axis = 1)
lms_cleaned_predict

LOAN_AMT      ROI  PRE_EMI          EMI EMI_PAID   TOTAL_PAID  \
0       4.0535e+06  17.1676        0      68239.8        1        46387   
1       1.3257e+07  15.6069  28441.7       194918        1       193884   
2      1.32114e+07  16.5433        0       202948        1       137957   
3      6.15531e+06  16.5433   451448       104347        1      70931.7   
4      9.49928e+06  18.9156   188502       178778        0       131790   
5      5.40066e+06  13.7341  5627.39      75269.7        0      51165.7   
6      4.30872e+06  17.4797  24033.5        73971        0      50282.9   
7      7.68864e+06  16.5433        0       118111        1      80287.8   
8       1.7252e+07  13.7341   167786       269322        0       183076   
9      1.13752e+07  19.0404  20453.4       230513        1       156695   
10     3.41853e+06  13.7341        0      47967.5        0      32606.6   
11     4.09404e+06  15.6069   547451      65269.3        1      44367.8   
12     7.65661e+06  13.7341   7979.5       111620        0      75875.5   
13     1.48421e+07  17.4797        0       472946        1       321492   
14      9.6246e+06  14.0462        0       149159        1       101393   
15     3.68305e+06  13.7341  5117.21      51368.7        0      34918.6   
16     7.07157e+06  15.6069  37929.7       103974        1        70678   
17     9.45816e+06  15.6069  44060.6       150045        1       101995   
18     6.75583e+07  16.5433   890694  1.68868e+06        0  1.80375e+07   
19     6.00518e+06  19.0404  11290.1       124207        1      84431.4   
20     3.97843e+06  15.2948  16542.1        74934        1      50937.5   
21     6.24002e+06   15.919        0        99948        1      67941.1   
22     9.03544e+06  17.7919        0       186881        1       127035   
23     1.71736e+07  17.7919  40352.5       355204        1       241455   
24     5.22236e+06  14.6705  16645.9      77127.1        1      52428.3   
25     6.11382e+06   18.104  44034.1       127743        1      86834.9   
26     1.86988e+06   18.104  13467.8      34058.1        1      23151.5   
27     5.37464e+07  14.5456   109816       830623        1       564628   
28     1.36877e+07   18.104  98583.1       242888        0       330213   
29     5.47973e+07  17.7919   386267  2.65827e+06        1    1.807e+06   
...            ...      ...      ...          ...      ...          ...   
13158  1.46827e+06  15.6069        0            0        1            0   
13159       795687   18.978        0            0        1            0   
13160  1.53132e+06  13.4219        0            0        1            0   
13161  1.84359e+06  13.4219        0            0        1            0   
13162  1.87662e+06  17.7919        0            0        1            0   
13163  2.50269e+06  13.4219        0            0        1            0   
13164  1.72649e+06  13.4219        0            0        1            0   
13165  2.64781e+06  13.4219        0            0        1            0   
13166  2.34783e+06  13.4219        0            0        1            0   
13167   2.4203e+06  13.4219        0            0        1            0   
13168  1.10796e+06  19.0404        0            0        1            0   
13169  2.70233e+06  13.4219        0            0        1            0   
13170  8.55739e+06  12.4231        0            0        1            0   
13171  1.04365e+06  13.4219        0            0        1            0   
13172  4.20363e+06  15.1075        0            0        1            0   
13173       795687  13.4219        0            0        1            0   
13174  2.17688e+06  14.6705        0            0        1            0   
13175  2.05678e+06  14.6705        0            0        1            0   
13176   3.7237e+06  14.6705        0            0        1            0   
13177  1.32114e+06  17.1052        0            0        1            0   
13178  1.11295e+06  16.2312        0            0        1            0   
13179   1.5813e+06  14.0462        

In [117]:
predictions = model1.predict(lms_cleaned_predict)

In [125]:
k = list(predictions)
k

[array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], d

In [60]:
lms_dg3 = pd.merge(lms_dg2,train)
lms_dg3.drop(['CUSTOMERID','AGREEMENTID'],inplace = True,axis=1)

In [63]:
lms_dg3_labels = lms_dg3['FORECLOSURE']
lms_dg3.drop(['FORECLOSURE'],axis = 1,inplace=True)


KeyError: 'FORECLOSURE'

In [64]:
lms_dg3

LOAN_AMT      ROI  PRE_EMI          EMI EMI_PAID TOTAL_PAID TENURE  \
0     1.17101e+07  13.7341  7994.27       184544        0     125447    120   
1     1.92903e+07  13.7341   100505       279448        0     312837    180   
2     3.93339e+06  16.2312  5947.63      62983.5        1      42814    180   
3     1.00226e+07  13.7341  60322.2       145192        0    98696.7    180   
4     7.75594e+06  15.6069  27732.8       120218        1      81720    180   
5          954408  13.7341  1325.13      13827.7        0    9399.61    180   
6      6.6057e+06  15.6069  37790.5      95533.1        0    64940.1    300   
7     3.29603e+07  13.7341   225933       464308        0     315620    300   
8     8.40726e+06  13.7341   185121       110624        0    75198.4    216   
9     1.46649e+07  15.6069   141577       215617        1     146569    180   
10    4.34378e+06  13.4219        0      70870.2        1    48175.1    240   
11    4.08065e+06  13.7341        0       102126        1    69421.4     84   
12     2.1665e+06  14.0462        0      31372.5        1    21325.9    240   
13    3.75324e+06  15.6069  39747.3      58405.2        1    39701.8    180   
14    9.00777e+06  14.0462        0       129328        1    87912.9    300   
15    4.61319e+06  15.2948        0      20612.4        1    14011.6    180   
16    6.38051e+07  15.6069   228141       989356        0     637699    180   
17    6.00518e+07  19.0404        0  1.21691e+06        1     827215    120   
18    6.15722e+06  16.5433        0        87642        1    59575.9    300   
19    7.82946e+06  14.0462        0       111550        1    75827.4    299   
20    6.91978e+06  16.2312        0       110165        1    74886.1    180   
21    5.02934e+07  16.5433   694678       873321        1     593653    180   
22    7.65661e+06  18.4161   165633       155157        1     105471    120   
23    3.27428e+07  15.6069        0       502982        0     341910    180   
24    2.33076e+07  18.4161   157154       472314        1     321063    120   
25    7.80674e+06  15.6069  36368.2       123847        1    84186.7    168   
26    5.38205e+06   15.482        0      82200.1        1    55876.7    180   
27    7.58154e+06  18.4161  85199.3       282695        1     192166    180   
28    1.62896e+07  15.6069  44268.2       256121        1     174102    240   
29    1.20104e+07  15.6069  23313.5       205872        1     139945    240   
...           ...      ...      ...          ...      ...        ...    ...   
5962  1.44275e+06  12.4231  2807.55            0        1    1995.22    204   
5963  1.49868e+06  14.3583   190158            0        1    6524.63    240   
5964    1.156e+06  15.6069  3390.61            0        0    2409.58    180   
5965  2.62727e+07  13.1098   107828            0        0    76629.1    180   
5966  2.34421e+06  17.4797     6372            0        1    4559.44    180   
5967  5.32997e+06  12.7977  12814.6            0        1    9106.86    108   
5968  1.52382e+06  14.9826   3574.4            0        0    2540.19    180   
5969  2.12283e+06  13.7341  25457.2            0        1    3765.25    180   
5970  5.37291e+06  13.7341  11551.3            0        1    8209.09    180   
5971  2.85246e+06  17.4797   136721            0        1     7644.6    180   
5972  1.57636e+06   18.104  7148.79            0        1    5080.38    180   
5973  1.39794e+06  13.4219  2938.53            0        1     2088.3    156   
5974  1.65143e+06  15.8566  4082.67            0        1    2914.02    180   
5975  2.37955e+06  19.6023  7303.01            0        0    5189.98    180   
5976   4.0535e+06  13.7341  8714.18            0        1    6192.85    180   
5977  1.07609e+07  12.1734  19489.5            0        1    14573.1    180   
5978   1.5013e+06  19.6023  4378.96            0        1    3274.33    120   
5979  7.50498e+06  10.6127   150109            0        1    8845.63    192   
5980  7.22016e+06  15.2948        0            0        1  

In [75]:
model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(32, activation='sigmoid', input_dim=39))
model.add(Dense(16, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [76]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [77]:
model.fit(lms_dg3, lms_dg3_labels, epochs = 3, batch_size = 32)

Epoch 1/3
5992/5992 [==============================] - 1s 86us/step - loss: 0.5604 - acc: 0.7612
Epoch 2/3
5992/5992 [==============================] - 0s 56us/step - loss: 0.5507 - acc: 0.7612
Epoch 3/3
5992/5992 [==============================] - 0s 56us/step - loss: 0.5501 - acc: 0.7612
